# Generated by Django 4.1.5 on 2023-02-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hello_ca", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="depertment",
            name="short_name",
            field=models.CharField(max_length=8),
        ),
    ]
