# Generated by Django 4.1.5 on 2023-02-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hello_ca", "0003_remove_depertment_short_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="name",
            new_name="first_name",
        ),
        migrations.AddField(
            model_name="employee",
            name="first_name_kana",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="last_name",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="last_name_kana",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
