# Generated by Django 4.1.5 on 2023-02-12 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hello_ca", "0004_rename_name_employee_first_name_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Depertment",
            new_name="Department",
        ),
        migrations.RenameField(
            model_name="employee",
            old_name="depertment",
            new_name="department",
        ),
    ]
